CREATE TABLE CATEGORY(

	ID BIGINT AUTO_INCREMENT,
	NAME NVARCHAR(50),
	DESCRIPTION NVARCHAR(250),
	IMAGE_URL NVARCHAR(100),
	IS_ACTIVE BIT,
	
	CONSTRAINT PK_CATEGORY_ID PRIMARY KEY(ID)

);

INSERT INTO CATEGORY (NAME, DESCRIPTION, IMAGE_URL, IS_ACTIVE) VALUES ('Television','This is some description for Television','CAT_1.img',1);
INSERT INTO CATEGORY (NAME, DESCRIPTION,IMAGE_URL,IS_ACTIVE) VALUES ('Mobile','This is some description for mobiles','CAT_2.img',1);
INSERT INTO CATEGORY (NAME, DESCRIPTION,IMAGE_URL,IS_ACTIVE) VALUES ('Laptop','This is some description for laptops','CAT_3.img',1);

CREATE TABLE USER_DETAILS(
	ID BIGINT AUTO_INCREMENT,
	FIRST_NAME NVARCHAR(100),
	LAST_NAME NVARCHAR(100),
	ROLE NVARCHAR(20),
	IS_ENABLED BIT,
	PASSWORD NVARCHAR(100),
	EMAIL NVARCHAR(100),
	CONTACT_NUMBER NVARCHAR(20),
	CONSTRAINT PK_USER_ID PRIMARY KEY (ID)
);

INSERT INTO USER_DETAILS (FIRST_NAME, LAST_NAME, ROLE, IS_ENABLED, PASSWORD, EMAIL, CONTACT_NUMBER) 
	VALUES ('VIRAT', 'KOHLI', 'ADMIN', 1, '$2a$10$ufI94gEZfmW8axRktml8Duo0aimh/K8epwcWRQSiLaMpppOWEc6m6', 'VIRAT.KOHLI@ADMIN.COM', '+91-9123-067-808');
INSERT INTO USER_DETAILS (FIRST_NAME, LAST_NAME, ROLE, IS_ENABLED, PASSWORD, EMAIL, CONTACT_NUMBER) 
	VALUES ('RAVINDRA', 'JADEJA', 'SUPPLIER', 1, '$2a$10$Ff7g14owmE2m3qz2Me/gFemAoF/f6htb8EaQiQN4TR5mbW/2vIv.y', 'RAVINDRA.JADEJA@SUPPLIER.COM', '+91-9123-067-456');
INSERT INTO USER_DETAILS (FIRST_NAME, LAST_NAME, ROLE, IS_ENABLED, PASSWORD, EMAIL, CONTACT_NUMBER) 
	VALUES ('RAVICHANDRAN', 'ASHWIN', 'SUPPLIER', 1, '$2a$10$G/7Fc3tPn.qHuTbaRU51hubpXMULSejCf0nTOkjvHX1HhTqgTSq4i', 'RAVICHANDRAN.ASHWIN@SUPPLIER.COM', '+91-9123-067-389');
INSERT INTO USER_DETAILS (FIRST_NAME, LAST_NAME, ROLE, IS_ENABLED, PASSWORD, EMAIL, CONTACT_NUMBER) 
	VALUES ('ADMIN', 'USER', 'ADMIN', 1, '$2a$10$INKfXQlQDlkZW.92RC77vOWp/cUr4.7k9qvJv84.U3Qxu7N01vQr6', 'ADMIN@USER.COM', '+91-9423-067-389');


CREATE TABLE PRODUCT(
	ID BIGINT AUTO_INCREMENT,
	CODE NVARCHAR(50),
	NAME NVARCHAR(100),
	BRAND NVARCHAR(100),
	DESCRIPTION NVARCHAR(250),
	UNIT_PRICE DECIMAL(10,2),
	QUANTITY BIGINT,
	IS_ACTIVE BIT,
	CATEGORY_ID BIGINT,
	SUPPLIER_ID  BIGINT,
	PURCHASES BIGINT DEFAULT 0,
	VIEWS BIGINT DEFAULT 0,
	CONSTRAINT PK_PRODUCT_ID PRIMARY KEY (ID),
	CONSTRAINT FK_PRODUCT_CATEGORY_ID FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY (ID),
	CONSTRAINT FK_SUPPLIER_CATEGORY_ID FOREIGN KEY (SUPPLIER_ID) REFERENCES USER_DETAILS (ID)
);

INSERT INTO PRODUCT(CODE, NAME, BRAND, DESCRIPTION, UNIT_PRICE, QUANTITY, IS_ACTIVE, CATEGORY_ID, SUPPLIER_ID)
     VALUES ('PRDABC123DEFX', 'iPhone 5s', 'Apple', 'An outdated over-exagerrated phone', 18000, 5, 1, 2, 2);
INSERT INTO PRODUCT(CODE, NAME, BRAND, DESCRIPTION, UNIT_PRICE, QUANTITY, IS_ACTIVE, CATEGORY_ID, SUPPLIER_ID)
     VALUES ('PRDDEF123DEFX', 'Samsung s7', 'Samsung', 'A nice phone by samsung!', 15000, 3, 1, 2, 3);
INSERT INTO PRODUCT(CODE, NAME, BRAND, DESCRIPTION, UNIT_PRICE, QUANTITY, IS_ACTIVE, CATEGORY_ID, SUPPLIER_ID)
     VALUES ('PRDPQR123WGTX', 'Google Pixel', 'Google', 'This is one of the best android smart phone available in the market right now!', 20000, 5, 1, 2, 2);
INSERT INTO PRODUCT(CODE, NAME, BRAND, DESCRIPTION, UNIT_PRICE, QUANTITY, IS_ACTIVE, CATEGORY_ID, SUPPLIER_ID)
     VALUES ('PRDMNO123PQRX', 'Macbook Pro', 'Apple', 'This is one of the best laptops available in the market right now!', 54000, 2, 1, 3, 2);
INSERT INTO PRODUCT(CODE, NAME, BRAND, DESCRIPTION, UNIT_PRICE, QUANTITY, IS_ACTIVE, CATEGORY_ID, SUPPLIER_ID)
     VALUES ('PRDABCXYZDEFX', 'Dell Latitude E6510', 'Dell', 'This is one of the best laptop series from dell that can be used!', 36000, 5, 1, 3, 2);
     
CREATE TABLE CART(
	ID BIGINT AUTO_INCREMENT,
        USER_ID BIGINT,
        GRAND_TOTAL DECIMAL(10,2),
        CART_LINES BIGINT,
        CONSTRAINT PK_CART_ID PRIMARY KEY (ID),
	CONSTRAINT FK_USER_CART_ID FOREIGN KEY (USER_ID) REFERENCES USER_DETAILS (ID),
);

CREATE TABLE ADDRESS(
     ID BIGINT AUTO_INCREMENT , 
     ADDRESS_LINE_ONE NVARCHAR(255),
     ADDRESS_LINE_TWO NVARCHAR(255),
     BILLING BOOLEAN(1),
     CITY NVARCHAR(255),
     COUNTRY NVARCHAR(255), 
     POSTAL_CODE NVARCHAR(255),
     SHIPPING BOOLEAN(1),
     STATE NVARCHAR(255),
     USER_ID BIGINT,
     CONSTRAINT PK_ADDRESS_ID PRIMARY KEY (ID),
     CONSTRAINT FK_USER_ID FOREIGN KEY (USER_ID) REFERENCES USER_DETAILS (ID)
);
