CREATE TABLE CATEGORY(

	ID BIGINT AUTO_INCREMENT,
	NAME NVARCHAR(50),
	DESCRIPTION NVARCHAR(250),
	IMAGE_URL NVARCHAR(100),
	IS_ACTIVE BIT,
	
	CONSTRAINT PK_CATEGORY_ID PRIMARY KEY(ID)

);

INSERT INTO CATEGORY (NAME, DESCRIPTION, IMAGE_URL, IS_ACTIVE) VALUES ('Television','This is some description for Television','CAT_1.img',1);
INSERT INTO CATEGORY (NAME, DESCRIPTION,IMAGE_URL,IS_ACTIVE) VALUES ('Mobile','This is some description for mobiles','CAT_2.img',1);
INSERT INTO CATEGORY (NAME, DESCRIPTION,IMAGE_URL,IS_ACTIVE) VALUES ('Laptop','This is some description for laptops','CAT_3.img',1);

CREATE TABLE USER_DETAILS(
	ID BIGINT AUTO_INCREMENT,
	FIRSTNAME NVARCHAR(100),
	LASTNAME NVARCHAR(100),
	ROLE NVARCHAR(20),
	IS_ENABLED BIT,
	PASSWORD NVARCHAR(100),
	EMAIL NVARCHAR(100),
	CONTACT_NUMBER NVARCHAR(20),
	CONSTRAINT PK_USER_ID PRIMARY KEY (ID)
);

INSERT INTO USER_DETAILS (FIRSTNAME, LASTNAME, ROLE, IS_ENABLED, PASSWORD, EMAIL, CONTACT_NUMBER) 
	VALUES ('VIRAT', 'KOHLI', 'ADMIN', 1, 'ADMINUSER123', 'VIRAT.KOHLI@ADMIN.COM', '+91-9123-067-808');
INSERT INTO USER_DETAILS (FIRSTNAME, LASTNAME, ROLE, IS_ENABLED, PASSWORD, EMAIL, CONTACT_NUMBER) 
	VALUES ('RAVINDRA', 'JADEJA', 'SUPPLIER', 1, 'SUPPLIER123', 'RAVINDRA.JADEJA@SUPPLIER.COM', '+91-9123-067-456');
INSERT INTO USER_DETAILS (FIRSTNAME, LASTNAME, ROLE, IS_ENABLED, PASSWORD, EMAIL, CONTACT_NUMBER) 
	VALUES ('RAVICHANDRAN', 'ASHWIN', 'SUPPLIER', 1, 'SUPPLIER456', 'RAVICHANDRAN.ASHWIN@SUPPLIER.COM', '+91-9123-067-389');

CREATE TABLE PRODUCT(
	ID BIGINT AUTO_INCREMENT,
	CODE NVARCHAR(50),
	NAME NVARCHAR(100),
	BRAND NVARCHAR(100),
	DESCRIPTION NVARCHAR(250),
	UNIT_PRICE DECIMAL(10,2),
	QUANTITY BIGINT,
	IS_ACTIVE BIT,
	CATEGORY_ID BIGINT,
	SUPPLIER_ID  BIGINT,
	PURCHASES BIGINT DEFAULT 0,
	VIEWS BIGINT DEFAULT 0,
	CONSTRAINT PK_PRODUCT_ID PRIMARY KEY (ID),
	CONSTRAINT FK_PRODUCT_CATEGORY_ID FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY (ID),
	CONSTRAINT FK_SUPPLIER_CATEGORY_ID FOREIGN KEY (SUPPLIER_ID) REFERENCES USER_DETAILS (ID)
);

INSERT INTO [PRODUCT]([CODE], [NAME], [BRAND], [DESCRIPTION], [UNIT_PRICE], [QUANTITY], [IS_ACTIVE], [CATEGORY_ID], [SUPPLIER_ID])
     VALUES ('PRDABC123DEFX', 'iPhone 5s', 'Apple', 'An outdated over-exagerrated phone', 18000, 5, 1, 2, 2)
INSERT INTO [PRODUCT]([CODE], [NAME], [BRAND], [DESCRIPTION], [UNIT_PRICE], [QUANTITY], [IS_ACTIVE], [CATEGORY_ID], [SUPPLIER_ID])
     VALUES ('PRDDEF123DEFX', 'Samsung s7', 'Samsung', 'A nice phone by samsung!', 15000, 3, 1, 2, 3)
INSERT INTO [PRODUCT]([CODE], [NAME], [BRAND], [DESCRIPTION], [UNIT_PRICE], [QUANTITY], [IS_ACTIVE], [CATEGORY_ID], [SUPPLIER_ID])
     VALUES ('PRDPQR123WGTX', 'Google Pixel', 'Google', 'This is one of the best android smart phone available in the market right now!', 20000, 5, 1, 2, 2)
INSERT INTO [PRODUCT]([CODE], [NAME], [BRAND], [DESCRIPTION], [UNIT_PRICE], [QUANTITY], [IS_ACTIVE], [CATEGORY_ID], [SUPPLIER_ID])
     VALUES ('PRDMNO123PQRX', 'Macbook Pro', 'Apple', 'This is one of the best laptops available in the market right now!', 54000, 2, 1, 3, 2)
INSERT INTO [PRODUCT]([CODE], [NAME], [BRAND], [DESCRIPTION], [UNIT_PRICE], [QUANTITY], [IS_ACTIVE], [CATEGORY_ID], [SUPPLIER_ID])
     VALUES ('PRDABCXYZDEFX', 'Dell Latitude E6510', 'Dell', 'This is one of the best laptop series from dell that can be used!', 36000, 5, 1, 3, 2)
